### ISSUE TITLE
Kibana link checking is broken

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs#1805]
The Kibana link checker doesn't seem to be catching broken links.

https://github.com/elastic/docs/blob/0cee4e4715554515b2e297fe1113708ac03c9cda/build_docs.pl#L334-L399

Here's an example of a broken link: https://github.com/elastic/kibana/pull/63295.

**Comment by gtback** [comment]
I'm only starting to understand how Kibana link checking works. @nik9000 gave me an overview this morning. It might take me a little while to wrap my head around it all.

**Comment by gtback** [comment]
I figured out why this was broken (at least for elastic/kibana#63295):

The only links that are checked are those that are located in the root Doc Links file (which has moved and been renamed between versions of Kibana)

If you do something like this in a different file, and then build URLs in those files, those URLs won't be checked. 

```
import { ELASTIC_WEBSITE_URL, DOC_LINK_VERSION } from 'ui/documentation_links';
```

This is what @lcawl is trying to fix in elastic/kibana#88107.

**Comment by gtback** [comment]
I'm tempted to close this, because I don't think looking through all of the Kibana code for links is feasible, but I'd like to track down why elastic/kibana#87721 *wasn't* failing as well.

**Comment by gtback** [comment]
I believe elastic/kibana#94274 (which prevents the `doc_links_service.ts` from being checked) is the ultimate root cause of this (along with elastic/kibana#88107: some of the links aren't in that file so aren't being checked). 

Order of operations for resolving this:

- [ ] Fix #2081.
- [ ] Ensure elastic/kibana#94274 passes, then merge it in.
- [ ] Confirm elastic/kibana#87721 still fails. I merged in some of the changes from elastic/kibana#87721, so it's already failing, but merging in the latest should reduce the diff and it should still fail.
- [ ] Fix the link in elastic/kibana#87721 to confirm it passes.
- [ ] Close this issue

**Comment by gtback** [comment]
elastic/kibana#87721 is passing! 🙌🏻 So I'm confident we have this fixed. The actual link will get fixed once that's merged, but that's not a blocker here.
