### ISSUE TITLE
[Meta] Doc Enhancements Wishlist

### ISSUE THREAD

**Issue by debadair** [elastic/docs#336]
This meta-issue is a collection of the various issues we have open regarding non-content doc enhancements:

- [Doc infrastructure changes](doc-infra): build, validate, automate
- [Interactive page widgets](doc-widgets)
- [Doc architecture and design](doc-design)

>There's some overlap and interaction between the different types of enhancements, so listing everything here for the time being.

### Build and validation
- [x] Make doc builds more modular #249 
- [x] Separate repos for doc infra and generated docs #153 
- [ ] Add validation step for identifying unresolved attributes #220 
- [ ] Add a check for pages deleted in newer versions (automate redirects?) #17, #1825
- [x] Automatically generate previews #483
- [ ] Enable comments on previews #1211
- [ ] Support per-page diffs in previews #1089

### Rendering
- [ ] Add tooling to generate "jump" lists #324 
- [ ] Improve the rendering of multiple callouts #265 
- [ ] Render AsciiDoctor "thematic breaks" #1130 
- [x] Support embedded videos #995 

### Alternative outputs
- [x] Offline docs (Docker image for ECE/air-gapped networks that is self contained)
- [ ] PDF docs (archive EOL docs) #61 
- [ ] ~~Blog posts (uploadable HTML) #10~~
- [ ] Deploy pre-release Cloud doc builds internally #766
- [ ] Fix building docs on Windows #1111

### Automation and tooling
- [ ] Automate screencaps [dev-#860](https://github.com/elastic/dev/issues/860)
- [x] Automatically rebuild affected docs with the shared attributes change #1180
- [ ] Automatically rebuild old docs when version list changes #59 
- [ ] Automate bumping doc versions #253 
- [x] Run release builds remotely #337

## [Interactive page widgets](#doc-widgets)
- [x] Copy as curl should support configuring the Elasticsearch host (and Cloud)  #335 
- [ ] Add "copy code" functionality for command examples #319 
- [ ] Add "Copy for Powershell" #210 
- [ ] Disable invalid options in the version select box #291 
- [ ] Add widget for displaying platform-specific instructions #260 
- [x] Add a documentation feedback link to each page #681 
- [ ] Make Edit link more prominent and consider adding link for creating GitHub issues #1244 
- [ ] Enable pop-ups for glossary terms. #1212

## [Doc Design](#doc-design)
- [ ] Doc {re}design [dev-#705](https://github.com/elastic/dev/issues/705) 
- [ ] Deprecated stuff should show up as deprecated in the TOC #325 
- [x] Temporary CSS fixes #229 
- [x] Inconsistent style in definition lists #126
- [ ] Search titles 
- [ ] ~~Automate inserting " ... to learn more about X, see [X-ing](bla) in the Y book."~~
- [ ] Support improved/customized landing pages: Observability, Clients #1114 client, Kibana, etc.

**Comment by kellyemurphy** [comment]
@debadair can we add "Get feedback on pages" under the interactive widget? A 👍 or 👎 would be a good start, but a small text box that opens with the 👎 would also be nice.

**Comment by nrichers** [comment]
@kellyemurphy @debadair I opened an issue for adding a feedback mechanism and linked to it in the root comment.

**Comment by aravindputrevu** [comment]
Folks - I came to docs repo to raise the issue of documentation feedback on each page. Happy to know that, we already thought about it. 

But saw it also got closed because, cloud addressed it using a different mechanism. But it still could be a great feature to implement. Are we still thinking about it?

**Comment by kellyemurphy** [comment]
@nik9000 could we get a feature where we can get keyword popups for glossary words? It might be helpful to have those definitions in-line rather than having to navigate to a separate page and back again.

**Comment by nik9000** [comment]
I think an inline glossary would be really useful. I'm not sure how to do it in a friendly way, but it is worth thinking about!

**Comment by debadair** [comment]
@aravindputrevu Cloud is blazing the trail, but the intent is that once they have something that's workable we can use that mechanism across the docs.

**Comment by aravindputrevu** [comment]
Yeah sure. This is one constant request from community to enhance the docs experience and take feedback on how far a chapter solve their problem.

**Comment by alaudazzi** [comment]
@aravindputrevu that's one of the priorities in our Cloud doc roadmap. Check [#26](https://github.com/elastic/qualtrics-surveys/issues/26) for more background.

**Comment by szabosteve** [comment]
@debadair Can we add "Enable support for mathematical formulae" under "Rendering"? I've already opened an issue: https://github.com/elastic/docs/issues/1765

**Comment by debadair** [comment]
Closing in favor of tracking the individual issues on a project board. See also  #1340 and #1343.
