### ISSUE TITLE
Improve release notes 

### ISSUE THREAD

**Issue by nrichers** [elastic/docs#945]
We want to create a better release notes experience for Elastic Stack products by providing a single entry point into content for new releases. 

Today, the lack of consistency and the multiple approaches among different Elastic Stack products make our release notes/breaking changes/what’s new/release highlights content confusing.

### Old

![image](https://user-images.githubusercontent.com/15148011/59881181-b89f3e00-9363-11e9-8bbf-d2ff5b383cb1.png)

* Disjointed: **Release Highlights** and **Release Notes** go together, as do **Limitations** and **Breaking Changes**, but these sections aren't next to each other
* Just more links: Click on **Release Highlights** or **Release Notes** and the first thing you see is ... more links
* Likely mislabelled: **Release Notes** consist of a generated changelog

### New

![image](https://user-images.githubusercontent.com/15148011/59881188-bccb5b80-9363-11e9-88c8-7b6d59ddae2f.png)

* A single entry point for all information, with existing content placed underneath
* Highlights get shown immediately when you click on **Release Notes**, other versions are readily available
* Changelog is a changelog

## Four links to give you everything
* [Release notes workgroup](https://docs.google.com/document/d/1XS4vlMQlXPUrM0M7Bzg3wEYbemPm7DB-aNZrOojga_I/edit#) (Elastic)
* [Proposed guidelines](https://docs.google.com/document/d/1_gnhg2OC2J7cIl9kymWH0CNk-dM4pH5eUNVAT3Asx5s/edit#) (look under "Release notes"; Elastic)
* [Example release notes](https://docs.google.com/document/d/14hAuBeOCV5HvpmHs3qKcXEGWkYyKQ5klHkC2QfCyIdc/edit#) (Elastic)
* [Working prototype derived from the example](https://cloud-docs-preview.firebaseapp.com/Kibana-release-notes/release-highlights.html) (public)

## I care about this. How do I get involved?

Talk to @gchaps @kellyemurphy @nrichers if you are interested in this initiative or add a comment to this issue. 

## Project phases

Phase 1 & 2 will be completed during DEVO (docs extreme virtual offsite), phase 3 and beyond will happen after DEVO.

### Phase 1 - Research
- [x] Identify what types of content exists, see [table](https://docs.google.com/document/d/1XS4vlMQlXPUrM0M7Bzg3wEYbemPm7DB-aNZrOojga_I/edit#heading=h.mnjpis689xp5) (Kelly)
- [ ] Define what each type of content should contain
   - [ ] See [definitions doc](https://docs.google.com/document/d/1yElO-s5NMiyIR95HEuQMHlcTP6pGTroSInedjbodvi8/edit) (All)
   - [ ] List out general responsible for what (dev or writer)
[ ] Explain automation in place and planned
   - [ ] The release notes script (check out the [docs wiki](https://wiki.elastic.co/display/DOC/Release+Notes))
   - [ ] Alexandros script for Cloud
   - [ ] Changelog for APM (written manually, but sourced from [Github entries](https://github.com/elastic/apm-agent-go/releases))
   - [ ] [Elasticsearch plans for changelog](https://github.com/elastic/apm-agent-go/releases)

### Phase 2 - Prototype
- [x] Draft an [example release notes](https://docs.google.com/document/d/14hAuBeOCV5HvpmHs3qKcXEGWkYyKQ5klHkC2QfCyIdc/edit#) (Gail, all) and mockup (Nik)
   - [ ] Need examples for major, minor, and patch releases
- [ ] Create [guidelines for writing release notes](https://docs.google.com/document/d/1KdFPRneGPE14wwCPZUVtrEIaAozXrA5RN0WpjX7y8jo/edit#heading=h.3c4da5gkza01) (Gail, all)
- [ ] Get feedback from other writers incorporate (All)
   - [ ] [See feedback](https://docs.google.com/document/d/1XS4vlMQlXPUrM0M7Bzg3wEYbemPm7DB-aNZrOojga_I/edit#bookmark=id.th7mgk2hgn2)
   - [ ] Update prototype with feedback (Nik)

### Phase 3 - Test
- [ ] A/B testing (All)
   - [ ] Planning (Kelly) 
   - [ ] Run tests on small group(s) 4-6 ppl
   - [ ] Analyze results
- [ ] Refine guidelines, mockup
- [ ] Create process proposal
- [ ] Draft initial template from test feedback

### Phase 4 - Roadshow
- [ ] Take this outside the writers, like dev, for consensus
- [ ] Identify key stakeholders and do a roadshow
- [ ] Invite comments from all 

### Phase 5 - Refine
- [ ] Refine templates
   - [ ] Each version level (major, minor, patch)
   - [ ] Possibly for each product?

### Phase 6 - Implement
- [ ] When agreed, document processes and responsibilities
- [ ] Sort out implementation and coordination details
- [ ] Make changes for releases going forward
- [ ] Address how to reference prior releases

### Deliverables
- [ ] [Definitions doc](https://docs.google.com/document/d/1yElO-s5NMiyIR95HEuQMHlcTP6pGTroSInedjbodvi8/edit) (what types of content goes where)
- [ ] [Release notes template](https://docs.google.com/document/d/14hAuBeOCV5HvpmHs3qKcXEGWkYyKQ5klHkC2QfCyIdc/edit#) and [guidelines](https://docs.google.com/document/d/14hAuBeOCV5HvpmHs3qKcXEGWkYyKQ5klHkC2QfCyIdc/edit#)
- [ ] Ideal world process workflow
- [ ] Plan to get from today to ideal

**Comment by lcawl** [comment]
When you have a good working example, I'd like to see how/if it works with the breaking changes and highlights in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/index.html). Changes might be required there too to work with the new design.

**Comment by gchaps** [comment]
@alexfrancoeur, @AlonaNadler Do you have any comments on this revised structure for the Release docs?

**Comment by gchaps** [comment]
@mellieA Could you provide comments on this structure.

**Comment by nrichers** [comment]
Superseded by /new project, closing.
