### ISSUE TITLE
Doc rendering issues after website redesign

### ISSUE THREAD

**Issue by karenzone** [elastic/docs#991]
Style changes to the (awesome!) new website redesign caused some unintended consequences to our documentation. 

- [x] #987 - Table columns don't wrap correctly
- [x] #988 - NOTE blocks are capitalized
- [x] #989 - xpack badge floats over dropdowns
- [x] #990 - links not highlighted on documentation
- [x] #992 - Code blocks should be monospaced
- [x] #993 - No header link back to `/guide` makes navigation difficult
- [x] https://github.com/elastic/docs/issues/997 - Hamburger menu doesn't expand on mobile
- [x] https://github.com/elastic/docs/issues/998 - Email form in footer doesn't render correctly on mobile
- [x] #999 - Branch selector drop-down is huge
- [x] https://github.com/elastic/docs/issues/1058 - 404 page doesn't have new style

**Comment by karenzone** [comment]
@nik9000 @brianjolly

**Comment by nik9000** [comment]
@brianjolly, I think you've made some progress on these, right?

**Comment by brianjolly** [comment]
@nik9000 , yes #997 and #998 are fixed now. 

It looks like #1058 is still outstanding

**Comment by gtback** [comment]
I think this can be closed now, since #1058 is no longer an issue.
